server:
    port: 8082
spring:
    servlet:
        session.timeout: 300s
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
finger:
  trialMode: true
  serverAddress: /local
  serverPort: 5000
  routeSqlite: C:\Users\Z259151\Repositorios\MIS_PROYECTOS\redbiopersona\face.db
persistence-service:
  enroll: http://localhost:8085/persistence/enroll
  delete: http://localhost:8085/persistence/delete